#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT=$1
PROJECT_SETUP_FILE="$DIR/$PROJECT/setup"

INSTALLED_PROJECTS_FILE="$HOME/.installed-projects"
[ -f "$INSTALLED_PROJECTS_FILE" ] || touch "$INSTALLED_PROJECTS_FILE"

if [ -z "$PROJECT" ]; then
  echo "Please specify a project to setup."
elif [ -f "$PROJECT_SETUP_FILE" ]; then
  
  echo "Checking for project setup script for: $PROJECT"
  if grep -q "$PROJECT$" "$PROJECT_SETUP_FILE"; then 
    echo "$PROJECT has already been setup"
  else
    echo "Running: $PROJECT_SETUP_FILE"
    bash "$PROJECT_SETUP_FILE"
    echo "$PROJECT" >> "$INSTALLED_PROJECTS_FILE"
  fi
  
else
  echo "Project $PROJECT not found."
fi
  