#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

sudo hostess add ppmspa.dev.daptiv.com 127.0.0.1

clone-with-options --strap 'ppmspa'
SPA_REPO="${SRC_DIR}/ppmspa"

DEBUG_LOG_CONFIG="${STRAP_DEBUG:-/dev/null}"
sudo tee "$NGINX_SITES_CONFIG_DIR/ppmspa.conf"  <<EOF 1>${DEBUG_LOG_CONFIG:-&1}
server {
  access_log $NGINX_LOG_DIR/ppmspa.dev.daptiv.com.access.log main;
  listen 80;
  server_name ppmspa.dev.daptiv.com;

  client_max_body_size 50M;

  location / {
    autoindex on;
    alias $SPA_REPO/output/package/;
  }
}
EOF

if [ ! -d "$SPA_REPO/output" ]; then
  #build spa if not already built.
  (
    cd $SPA_REPO
    yarn install
    yarn build:fast
  )
