#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if ! [ -d "$SRC_DIR/PpmSpa" ]; then
    echo 'cloning PpmSpa repo...'
    git clone git@github.com:daptiv/PpmSpa.git "$SRC_DIR/PpmSpa"
fi

echo "running strapfile..."
[ -f "$SRC_DIR/PpmSpa/strap.sh" ] && "$SRC_DIR/PpmSpa/strap.sh"
