#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo 'adding host entries for ppm...'
bash "$DIR/add-host-entries.sh"

echo 'setting up vm...'
bash "$DIR/setup-vm.sh"

echo 'add nginx config for ppm...'
sudo tee "$NGINX_SITES_CONFIG_DIR/ppm.conf" <<EOF
server {
  access_log $NGINX_LOG_DIR/devppm.daptiv.com.access.log main;
  listen 80;
  server_name devppm.daptiv.com;

  client_max_body_size 50M;

  location / {
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header Host \$http_host;
    proxy_redirect off;
    proxy_pass http://localvm.daptiv.com:80;
  }

  location /spa {
    autoindex on;
    alias $SRC_DIR/PpmSpa/output/package/;
  }
}
EOF

echo 'reload nginx config...'
sudo nginx -s reload

# Add the NatNetwork for VirtualBox
# vboxmanage natnetwork add --netname NatNetwork --network 10.0.2.0/24 --ipv6 off --enable 2>/dev/null
# vboxmanage natnetwork start --netname NatNetwork
