#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo 'adding host entries for ppm...'
bash "$DIR/add-host-entries.sh"

echo 'setting up vm...'
bash "$DIR/setup-vm.sh"

echo 'add nginx config for ppm...'
sudo tee "$NGINX_SITES_CONFIG_DIR/ppm.conf" <<EOF
server {
  access_log $NGINX_LOG_DIR/devppm.daptiv.com.access.log main;
  listen 80;
  server_name devppm.daptiv.com;

  client_max_body_size 50M;

  location /spa {
    autoindex on;
    alias $SRC_DIR/ppmspa/output/package/;
  }

  location / {
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header Host \$http_host;
    proxy_redirect off;
    proxy_pass http://localvm.daptiv.com:80;
  }
}

server {
  access_log $NGINX_LOG_DIR/dev.daptiv.com.access.log main;
  listen 80;
  server_name dev.daptiv.com;

  client_max_body_size 50M;

  location / {
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header Host \$http_host;
    proxy_redirect off;
    proxy_pass http://localvm.daptiv.com:80;
  }
}
EOF

