#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

clone-missing-repo "daptiv-pattern-library"
clone-with-options --git-flow "ppm-npmp-react-theme"
clone-with-options --git-flow "ppm-cmpt-react-theme"
