#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

clone-with-options         --git-flow ppm-cmpt-new-feature-popup
clone-with-options --strap --git-flow ppm-wrpr-new-feature-popup
clone-with-options --strap            ppm-vapi-new-feature-popup
clone-with-options --strap --git-flow new-feature-composer
