#!/usr/bin/env bash
set -e

REPOS=( ppm-mspa-projectdashboard ppm-vapi-projectdashboard )
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for REPO in ${REPOS[@]}
do
  if ! [ -d "$SRC_DIR/$REPO" ]; then
    printf "\n** Cloning $REPO repo **\n"
    git clone git@github.com:daptiv/$REPO.git "$SRC_DIR/$REPO"

    if [ -e "$SRC_DIR/$REPO/strap.sh" ]; then
      printf "\n** Running strapfile **\n"
      bash "$SRC_DIR/$REPO/strap.sh"
    fi
  fi
done
