#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

# make sure feature flag project is set up.
bash "$PROJECTS_DIR/setup feature-flag"

clone-with-options --strap 'ppm-mspa-projectdashboard'
clone-with-options --strap 'ppm-vapi-projectdashboard'
