#!/usr/bin/env bash

DAPTIV_DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile"

if ! nodenv versions | grep -q -E ' 6.11.3 '; then
  echo 'installing node 6.11.3...'
  nodenv install 6.11.3
  nodenv global 6.11.3
fi

if ! [ -f "$GOPATH/go/bin/hostess" ]; then
  echo 'installing hostess command line tool...'
  go get github.com/cbednarski/hostess/cmd/hostess
  
  ln -sfv "$GOPATH/go/bin/hostess" /usr/local/bin/hostess
fi

echo 'update default nginx config...'
sudo tee "$NGINX_CONFIG_DIR" <<EOF
daemon off;

user $USER staff;

worker_processes 2;
pid $NGINX_LOG_DIR/nginx.pid;

events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] $status '
                  '"$request" $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "http_x_forwarded_for"';

  access_log $NGINX_LOG_DIR/access.log main;
  error_log  $NGINX_LOG_DIR/error.log debug;

  sendfile on;

  tcp_nopush  on;
  tcp_nodelay off;

  gzip              on;
  gzip_http_version 1.0;
  gzip_comp_level   2;
  gzip_proxied      any;

  server_names_hash_bucket_size 128;
  server_names_hash_max_size 20000;
  proxy_headers_hash_bucket_size 128;
  proxy_headers_hash_max_size 20000;

  underscores_in_headers on;

  server {
    listen      80 default_server;
    server_name localhost;

    location / {
      root   $NGINX_CONFIG_DIR/public;
    }
  }

  include $NGINX_SITES_CONFIG_DIR/*;
}
EOF

echo 'setup ppm project...'
bash "$DAPTIV_DOTFILES/projects/setup" ppm
