#!/usr/bin/env bash

DAPTIV_DOTFILES="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile"

echo 'installing hostess command line tool...'
go get github.com/cbednarski/hostess/cmd/hostess
if [ -f "$GOPATH/go/bin/hostess" ] && ! [ -L "/usr/local/bin/hostess" ]; then
  ln -sv "$GOPATH/go/bin/hostess" /usr/local/bin/hostess
fi

echo 'setup ppm project...'
bash "$DAPTIV_DOTFILES/projects/setup" ppm
