#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

printf "\nThis script requires sudo access to configure nginx, hosts, etc. "
printf "If prompted, please enter your password.\n"
sudo -v
sudo /usr/bin/true

printf "\n** Proceeding with changes\n"

sudo hostess add ppm.dev.daptiv.com 127.0.0.1

sudo sed \
    "s|NGINX_LOG_DIR|$NGINX_LOG_DIR|" \
    <"$DIR/ppm-mspa-shared.nginx.conf" \
    >"$NGINX_SITES_CONFIG_DIR/ppm-mspa-shared.conf"

sudo mkdir -p "$NGINX_SITES_CONFIG_DIR/mspa-upstreams"
sudo mkdir -p "$NGINX_SITES_CONFIG_DIR/mspa-locations"

sudo nginx -t && sudo nginx -s reload
