#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

log-msg 'adding host entries for cognos 10.2.2...'
bash "$DIR/add-host-entries.sh"

log-msg 'setting up cognos 10.2.2 vm...'
bash "$DIR/setup-vm.sh"
