#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo 'adding host entries for cognos 10.2.2...'
bash "$DIR/add-host-entries.sh"

echo 'setting up cognos 10.2.2 vm...'
bash "$DIR/setup-vm.sh"

