#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

# make sure feature flag project is set up.
bash "$PROJECTS_DIR/setup" feature-flag

clone-missing-repo 'teammember-api'
clone-with-options --strap 'teammember-client'
