#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECTS_DIR="$DIR/.."

source "$PROJECTS_DIR/functions.sh"

clone-missing-repo "project-task-board-api"
clone-and-strap-repo "project-team-board"
